#
# Module manifest for module 'PSTouchSensor'
#
# Generated by: tylerleonhardt
#
# Generated on: 10/2/18
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSTouchSensor.psm1'

# Version number of this module.
ModuleVersion = '0.1.0'

# Supported PSEditions
CompatiblePSEditions = @( 'Core' )

# ID used to uniquely identify this module
GUID = '4dfd621d-c96c-4d55-95a2-5a0cb22d2729'

# Author of this module
Author = 'tylerleonhardt'

# Company or vendor of this module
CompanyName = 'tylerleonhardt'

# Copyright statement for this module
Copyright = '(c) tylerleonhardt. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Provides a PowerShell-friendly interface into Touch Sensors'

# Minimum version of the PowerShell engine required by this module
# PowerShellVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @( 'Microsoft.PowerShell.IoT' )

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @( 'Get-PSTouchSensor' )

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# List of all modules packaged with this module
ModuleList = @( 'PSTouchSensor.psm1' )

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @( 'IoT', 'TouchSensor' )

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/tylerl0706/PSTouchSensor/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/tylerl0706/PSTouchSensor'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '#0.1.0
Initial Release
'

    }

}

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
